name: app_marvel
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  intl: ^0.18.0
  riverpod: ^2.3.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon/marvel_icon.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true
  assets:
    - .env.production
    - .env.development
    - assets/
    - assets/app_icon/

flutter_intl:
  enabled: true
  main_locale: es
  class_name: I18n
